/* eslint-disable react-refresh/only-export-components */

import { createContext, useContext, useEffect } from 'react'
import { useLocalStorage } from '../hooks/useLocalStorage'

const LanguageContext = createContext(null)

const translations = {
  en: {
    'common.all': 'All',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.undo': 'Undo',
    'common.backToBrowse': 'Back to Browse',

    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.browse': 'Browse',
    'nav.create': 'Create',
    'nav.switchToEnglish': 'Switch to English',
    'nav.switchToFrench': 'Switch to French',

    'home.eyebrow': 'Defy the Conventional • Repoussez les frontieres',
    'home.titleLead': 'Master any subject with',
    'home.titleAccent': ' interactive flashcards',
    'home.description':
      'uoDecks helps Gee-Gees create, organize, and study digital flashcards with fast deck building, clean review sessions, and simple progress tracking.',
    'home.startLearning': 'Start Learning Now',
    'home.learnMore': 'Learn More',

    'browse.discover': 'Discover',
    'browse.title': 'Browse decks',
    'browse.description':
      'Search by name, description, category, or card content. Recently viewed decks stay visible so students do not need to remember exact titles.',
    'browse.searchPlaceholder': 'Search decks by name, description, category, or concept...',
    'browse.libraryOverview': 'Library Overview',
    'browse.availableDecks': 'available decks',
    'browse.courseCategories': 'course categories',
    'browse.matchingCurrentFilters': 'matching current filters',
    'browse.deckLibrary': 'Deck Library',
    'browse.decks': 'Decks',
    'browse.shown': 'shown',
    'browse.noDecksMatch': 'No decks match that search',
    'browse.noDecksMatchBody': 'Clear the current filters or create a new deck to keep building your study library.',
    'browse.viewRecentActivities': 'View Recent Activities',
    'browse.hideRecentActivities': 'Hide Recent Activities',
    'browse.recentActivity': 'Recent Activity',
    'browse.recentlyViewedDecks': 'Recently viewed decks',
    'browse.recentEmpty': 'Open or study a deck and it will appear here automatically.',
    'browse.deleteDeckTitle': 'Delete this deck?',
    'browse.deleteDeckBody': 'This permanently removes the deck from your library unless you immediately undo the action.',
    'browse.deleteDeckConfirm': 'Delete deck',
    'browse.toastDeckDeletedTitle': 'Deck deleted',
    'browse.toastDeckDeletedMessage': 'Undo is available for a few seconds if this was accidental.',

    'create.deckInfoTag': 'Deck information',
    'create.deckInfoTitle': 'Set the basics first',
    'create.requiredNote': 'Please fill out the required fields below with the red asterisk *',
    'create.draftCards': 'draft cards',
    'create.viewTips': 'View Builder Tips',
    'create.deckName': 'Deck name',
    'create.category': 'Category',
    'create.description': 'Description',
    'create.deckNamePlaceholder': 'e.g., Spanish Vocabulary',
    'create.categoryPlaceholder': 'e.g., Language, Science, History',
    'create.descriptionPlaceholder': 'Briefly explain what this deck helps students study.',
    'create.flashcardsTag': 'Flashcards',
    'create.flashcardsTitle': 'Write clear prompts and concise answers',
    'create.addCard': 'Add Card',
    'create.frontLabel': 'Front (question)',
    'create.backLabel': 'Back (answer)',
    'create.frontPlaceholder': 'Enter the question or term',
    'create.backPlaceholder': 'Enter the answer or definition',
    'create.remove': 'Remove',
    'create.saveChanges': 'Save Changes',
    'create.saveDeck': 'Save Deck',
    'create.tipsTag': 'Builder Tips',
    'create.tipsTitle': 'Make each card easy to review',
    'create.tip1': 'Keep one idea or definition per card so answers stay short and memorable.',
    'create.tip2': 'Use familiar course names or topics to make decks easier to find later.',
    'create.tip3': 'Write prompts that are specific enough to avoid vague guesses.',
    'create.tip4': 'If you remove a card by mistake, use undo from the toast message right away.',
    'create.discardTitle': 'Discard your changes?',
    'create.discardBody': 'Leaving this page now will remove any unsaved edits in the deck builder.',
    'create.discardConfirm': 'Discard changes',
    'create.validationTitle': 'Enter a deck name so the deck is recognizable in the library.',
    'create.validationCategory': 'Pick a course or category to keep the knowledge organized.',
    'create.validationDescription': 'Add a short description so students know what this deck covers.',
    'create.validationCards': 'Add at least two flashcards so the study session has meaningful progression.',
    'create.validationCardSide': 'Each flashcard needs both a front and a back.',
    'create.validationFrontRequired': 'Front side is required.',
    'create.validationBackRequired': 'Back side is required.',
    'create.toastFlashcardRemovedTitle': 'Flashcard removed',
    'create.toastFlashcardRemovedMessage': 'Undo to recover the deleted card without retyping it.',
    'create.toastFixTitle': 'Fix the highlighted fields',
    'create.toastFixMessage': 'The builder keeps incomplete cards from being saved to prevent study errors.',
    'create.toastSavedTitle': 'Deck saved',
    'create.toastUpdatedTitle': 'Deck updated',
    'create.toastSavedMessage': 'Your deck is ready for browsing and study sessions.',
    'create.editTag': 'Edit Deck',
    'create.createTag': 'Create Deck',
    'create.editTitle': 'Edit deck',
    'create.createTitle': 'Create new deck',
    'create.pageDescription':
      'Build a custom flashcard deck with structured fields, helpful prompts, and validation that prevents incomplete cards from reaching study mode.',
    'create.deckNotFoundTitle': 'Deck not found',
    'create.deckNotFoundBody': 'The deck you tried to edit is missing. Return to the library and choose another deck.',
    'create.backToBrowse': 'Back to browse',

    'study.backToDecks': 'Back to Decks',
    'study.tag': 'Absorb Information',
    'study.correct': 'Correct',
    'study.cards': 'Cards',
    'study.progress': 'Progress',
    'study.complete': 'complete',
    'study.shortcutReveal': 'SPACE: reveal',
    'study.shortcutWrong': 'W: Wrong',
    'study.shortcutCorrect': 'C: Correct',
    'study.shortcutRepeat': 'R: Repeat',
    'study.answer': 'Answer',
    'study.question': 'Question',
    'study.revealHint': 'Click or press space to reveal answer',
    'study.marked': 'Marked',
    'study.markedCorrect': 'correct',
    'study.markedWrong': 'wrong',
    'study.previous': 'Previous',
    'study.revealAnswer': 'Reveal Answer',
    'study.gotWrong': 'Got it Wrong',
    'study.gotCorrect': 'Got it Correct',
    'study.repeat': 'Repeat',
    'study.unavailableTitle': 'Study session unavailable',
    'study.unavailableBody': 'This deck could not be found. Return to the library and start another session.',

    'results.unavailableTitle': 'Results unavailable',
    'results.unavailableBody': 'This study summary is missing. Start a new session to generate fresh results.',
    'results.accuracy': 'accuracy',
    'results.tag': 'Analyzing Results',
    'results.title': 'Study session complete!',
    'results.finishedOn': 'finished on',
    'results.with': 'with',
    'results.correctAnswersOutOf': 'correct answers out of',
    'results.correct': 'correct',
    'results.needReview': 'need review',
    'results.new': 'New',
    'results.firstAttempt': 'first recorded attempt',
    'results.changeFromLast': 'change from last attempt',
    'results.studyAgain': 'Study Again',
    'results.editDeck': 'Edit Deck',
    'results.whatToReview': 'What to Review',
    'results.cardsNeedWork': 'Cards that still need work',
    'results.perfectRound': 'Perfect round. No missed cards in this session.',
    'results.responseBreakdown': 'Response Breakdown',
    'results.everyCard': 'Every studied card',
    'results.correctBadge': 'Correct',
    'results.reviewBadge': 'Review',

    'about.tag': 'About uoDecks',
    'about.title': 'About uOttawa FlashCards',
    'about.description':
      'The platform supports students who need to create, browse, study, and evaluate their learning materials while keeping the interface consistent and easy to understand.',
    'about.learnMore': 'Learn More',
    'about.showLess': 'Show Less',
  },
  fr: {
    'common.all': 'Tous',
    'common.cancel': 'Annuler',
    'common.close': 'Fermer',
    'common.undo': 'Annuler',
    'common.backToBrowse': 'Retour a parcourir',

    'nav.home': 'Accueil',
    'nav.about': 'A propos',
    'nav.browse': 'Parcourir',
    'nav.create': 'Creer',
    'nav.switchToEnglish': 'Passer en anglais',
    'nav.switchToFrench': 'Passer en francais',

    'home.eyebrow': 'Defiez le conventionnel • Repoussez les frontieres',
    'home.titleLead': 'Maitrisez n importe quelle matiere avec',
    'home.titleAccent': ' des cartes memoire interactives',
    'home.description':
      'uoDecks aide les Gee-Gees a creer, organiser et etudier des cartes memoire numeriques avec une creation rapide de paquets, des sessions claires et un suivi simple de la progression.',
    'home.startLearning': 'Commencer a apprendre',
    'home.learnMore': 'En savoir plus',

    'browse.discover': 'Decouvrir',
    'browse.title': 'Parcourir les paquets',
    'browse.description':
      'Recherchez par nom, description, categorie ou contenu des cartes. Les paquets recemment consultes restent visibles pour faciliter le retour.',
    'browse.searchPlaceholder': 'Rechercher des paquets par nom, description, categorie ou concept...',
    'browse.libraryOverview': 'Apercu de la bibliotheque',
    'browse.availableDecks': 'paquets disponibles',
    'browse.courseCategories': 'categories de cours',
    'browse.matchingCurrentFilters': 'correspondent aux filtres',
    'browse.deckLibrary': 'Bibliotheque de paquets',
    'browse.decks': 'Paquets',
    'browse.shown': 'affiches',
    'browse.noDecksMatch': 'Aucun paquet ne correspond',
    'browse.noDecksMatchBody': 'Effacez les filtres actuels ou creez un nouveau paquet pour continuer.',
    'browse.viewRecentActivities': 'Voir activites recentes',
    'browse.hideRecentActivities': 'Masquer activites recentes',
    'browse.recentActivity': 'Activite recente',
    'browse.recentlyViewedDecks': 'Paquets recemment consultes',
    'browse.recentEmpty': 'Ouvrez ou etudiez un paquet et il apparaitra ici automatiquement.',
    'browse.deleteDeckTitle': 'Supprimer ce paquet ?',
    'browse.deleteDeckBody': 'Cela supprime ce paquet de votre bibliotheque sauf si vous annulez tout de suite.',
    'browse.deleteDeckConfirm': 'Supprimer le paquet',
    'browse.toastDeckDeletedTitle': 'Paquet supprime',
    'browse.toastDeckDeletedMessage': 'Annulation disponible pendant quelques secondes.',

    'create.deckInfoTag': 'Informations du paquet',
    'create.deckInfoTitle': 'Commencez par les bases',
    'create.requiredNote': 'Veuillez remplir les champs requis avec l asterisque rouge *',
    'create.draftCards': 'cartes brouillon',
    'create.viewTips': 'Voir conseils du createur',
    'create.deckName': 'Nom du paquet',
    'create.category': 'Categorie',
    'create.description': 'Description',
    'create.deckNamePlaceholder': 'ex.: Vocabulaire espagnol',
    'create.categoryPlaceholder': 'ex.: Langue, Science, Histoire',
    'create.descriptionPlaceholder': 'Expliquez brievement ce que ce paquet aide a etudier.',
    'create.flashcardsTag': 'Cartes memoire',
    'create.flashcardsTitle': 'Ecrivez des questions claires et des reponses concises',
    'create.addCard': 'Ajouter une carte',
    'create.frontLabel': 'Recto (question)',
    'create.backLabel': 'Verso (reponse)',
    'create.frontPlaceholder': 'Entrez la question ou le terme',
    'create.backPlaceholder': 'Entrez la reponse ou la definition',
    'create.remove': 'Retirer',
    'create.saveChanges': 'Enregistrer les modifications',
    'create.saveDeck': 'Enregistrer le paquet',
    'create.tipsTag': 'Conseils du createur',
    'create.tipsTitle': 'Rendez chaque carte facile a reviser',
    'create.tip1': 'Gardez une seule idee ou definition par carte pour des reponses courtes.',
    'create.tip2': 'Utilisez des noms de cours ou sujets familiers pour retrouver les paquets.',
    'create.tip3': 'Ecrivez des questions assez precises pour eviter les reponses vagues.',
    'create.tip4': 'Si vous retirez une carte par erreur, utilisez annuler dans le toast.',
    'create.discardTitle': 'Ignorer vos modifications ?',
    'create.discardBody': 'Quitter maintenant supprimera les modifications non enregistrees.',
    'create.discardConfirm': 'Ignorer les modifications',
    'create.validationTitle': 'Entrez un nom de paquet reconnaissable dans la bibliotheque.',
    'create.validationCategory': 'Choisissez un cours ou une categorie pour organiser le contenu.',
    'create.validationDescription': 'Ajoutez une courte description pour expliquer le contenu du paquet.',
    'create.validationCards': 'Ajoutez au moins deux cartes pour une session pertinente.',
    'create.validationCardSide': 'Chaque carte memoire a besoin d un recto et d un verso.',
    'create.validationFrontRequired': 'Le recto est requis.',
    'create.validationBackRequired': 'Le verso est requis.',
    'create.toastFlashcardRemovedTitle': 'Carte retiree',
    'create.toastFlashcardRemovedMessage': 'Annulez pour recuperer la carte sans la ressaisir.',
    'create.toastFixTitle': 'Corrigez les champs en surbrillance',
    'create.toastFixMessage': 'Le createur bloque les cartes incompletes pour eviter des erreurs.',
    'create.toastSavedTitle': 'Paquet enregistre',
    'create.toastUpdatedTitle': 'Paquet mis a jour',
    'create.toastSavedMessage': 'Votre paquet est pret pour la navigation et les sessions.',
    'create.editTag': 'Modifier le paquet',
    'create.createTag': 'Creer un paquet',
    'create.editTitle': 'Modifier le paquet',
    'create.createTitle': 'Creer un nouveau paquet',
    'create.pageDescription':
      'Creez un paquet de cartes memoire avec des champs structures, des invites utiles et une validation qui bloque les cartes incompletes.',
    'create.deckNotFoundTitle': 'Paquet introuvable',
    'create.deckNotFoundBody': 'Le paquet a modifier est introuvable. Retournez a la bibliotheque.',
    'create.backToBrowse': 'Retour a parcourir',

    'study.backToDecks': 'Retour aux paquets',
    'study.tag': 'Assimiler l information',
    'study.correct': 'Correct',
    'study.cards': 'Cartes',
    'study.progress': 'Progression',
    'study.complete': 'termine',
    'study.shortcutReveal': 'ESPACE: reveler',
    'study.shortcutWrong': 'W: Faux',
    'study.shortcutCorrect': 'C: Correct',
    'study.shortcutRepeat': 'R: Refaire',
    'study.answer': 'Reponse',
    'study.question': 'Question',
    'study.revealHint': 'Cliquez ou appuyez sur espace pour reveler la reponse',
    'study.marked': 'Marque',
    'study.markedCorrect': 'correct',
    'study.markedWrong': 'faux',
    'study.previous': 'Precedent',
    'study.revealAnswer': 'Reveler la reponse',
    'study.gotWrong': 'Je me suis trompe',
    'study.gotCorrect': 'J ai bien repondu',
    'study.repeat': 'Refaire',
    'study.unavailableTitle': 'Session d etude indisponible',
    'study.unavailableBody': 'Ce paquet est introuvable. Retournez a la bibliotheque et recommencez.',

    'results.unavailableTitle': 'Resultats indisponibles',
    'results.unavailableBody': 'Ce resume d etude est introuvable. Lancez une nouvelle session.',
    'results.accuracy': 'precision',
    'results.tag': 'Analyse des resultats',
    'results.title': 'Session d etude terminee !',
    'results.finishedOn': 'termine le',
    'results.with': 'avec',
    'results.correctAnswersOutOf': 'bonnes reponses sur',
    'results.correct': 'correct',
    'results.needReview': 'a reviser',
    'results.new': 'Nouveau',
    'results.firstAttempt': 'premiere tentative enregistree',
    'results.changeFromLast': 'changement depuis la tentative precedente',
    'results.studyAgain': 'Etudier encore',
    'results.editDeck': 'Modifier le paquet',
    'results.whatToReview': 'A reviser',
    'results.cardsNeedWork': 'Cartes qui demandent encore du travail',
    'results.perfectRound': 'Tour parfait. Aucune carte manquee.',
    'results.responseBreakdown': 'Detail des reponses',
    'results.everyCard': 'Toutes les cartes etudiees',
    'results.correctBadge': 'Correct',
    'results.reviewBadge': 'A reviser',

    'about.tag': 'A propos de uoDecks',
    'about.title': 'A propos des cartes memoire uOttawa',
    'about.description':
      'La plateforme aide les etudiants a creer, parcourir, etudier et evaluer leurs contenus tout en gardant une interface simple.',
    'about.learnMore': 'En savoir plus',
    'about.showLess': 'Voir moins',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useLocalStorage('app-language', 'en')

  useEffect(() => {
    document.documentElement.lang = language
  }, [language])

  const t = (key) => {
    return translations[language]?.[key] ?? translations.en[key] ?? key
  }

  const toggleLanguage = () => {
    setLanguage((current) => (current === 'en' ? 'fr' : 'en'))
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)

  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }

  return context
}
